seed: 1
record_video: yes

environment:
  verbose: no
  render: yes
  num_envs: 200
  num_threads: 40
  simulation_dt: 0.0025
  control_dt: 0.01
  max_time: 10.
  gravity: -9.8107
  forwardVelRewardCoeff: 8
  torqueRewardCoeff: 0.00005
  clearanceRewardCoeff: 3
  slipRewardCoeff: 1
  globalRewardScale: 500
