seed: 1
record_video: yes

environment:
  verbose: no
  render: yes
  num_envs: 100
  num_threads: 40
  simulation_dt: 0.0025
  control_dt: 0.01
  max_time: 10.
  gravity: -9.8107
  forwardVelRewardCoeff: 4
  torqueRewardCoeff: 0.00025
  clearanceRewardCoeff: 6
  slipRewardCoeff: 1.
  orientRewardCoeff: 10
  gaitRewardCoeff: 0.01
  globalRewardScale: 500
