seed: 1
record_video: yes

environment:
  verbose: n
  render: True
  num_envs: 200
  num_threads: 40
  simulation_dt: 0.0025
  control_dt: 0.01
  max_time: 4.0
  gravity: -9.8107
  forwardVelRewardCoeff: 4
  torqueRewardCoeff: 0.00001
  clearanceRewardCoeff: 1
  globalRewardScale: 500
